---
- hosts: irp2
  become: yes
  tasks:
    - name: Install OS packages
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - python-pip
        - libxml2-dev
        - libxslt-dev
        - python3-dev
        - python-lxml
        - libz-dev
        - git
        - nginx

    - name: Configure Nginx Proxy
      template: src=nginx-irp2.conf.j2 dest=/etc/nginx/conf.d/irp2.conf
    - service: name=nginx state=restarted enabled=yes

    - name: Deploy application code
      copy: src=../.. dest=~/ mode=0755
      become: no
      tags: code

    - name: Install Python packages
      pip: requirements=~/IRP2/requirements.txt virtualenv=~/irp2venv virtualenv_python=python3.4
      become: no

    - name: Stop existing application
      command: killall python
      become: no
      ignore_errors: yes

  handlers:
    - name: restart Nginx
      service: name=ntpd state=restarted
