---

- name: Install Nginx
  apt: name=nginx update_cache=no state=installed

# - name: Copy the SSL certificate to the remote server
#   copy: content="{{ ssl_crt }}" dest={{ ssl_dest_dir }}/{{ application_name }}.crt
#   notify: reload nginx
#
# - name: Copy the SSL private key to the remote server
#   copy: content="{{ ssl_key }}" dest={{ ssl_dest_dir }}/{{ application_name }}.key
#   notify: reload nginx

- name: Create the Nginx configuration file
  template: src=nginx-irp2.conf.j2 dest=/etc/nginx/sites-available/irp2.conf

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Ensure that the application site is enabled
  file: state=link src=/etc/nginx/sites-available/irp2.conf dest=/etc/nginx/sites-enabled/irp2.conf

- name: Ensure Nginx service is enabled
  service: name=nginx state=restarted enabled=yes
