    - name: Create Solr user
      user: name=solr system=yes

    - stat: path=/opt/solr
      register: s

    - name: Download Solr
      get_url: url=http://mirrors.ibiblio.org/apache/lucene/solr/6.1.0/solr-6.1.0.tgz dest=/tmp/solr-6.1.0.tgz
      when: s.stat.exists is defined and s.stat.exists == False

    - name: Extract Solr installer
      command: tar xzf /tmp/solr-6.1.0.tgz solr-6.1.0/bin/install_solr_service.sh --strip-components=2
      args:
        chdir: /tmp/
        creates: /opt/solr

    - name: Run Solr installer (starts Solr service)
      command: bash ./install_solr_service.sh solr-6.1.0.tgz -f -i /opt -d /var/solr -u solr -s solr -p 8983
      args:
        chdir: /tmp/
        creates: /opt/solr

    - name: Deploy Solr SystemD Service
      copy: src=solr.service dest=/etc/systemd/system/solr.service

    - name: Enable Solr service
      service: name=solr enabled=yes state=restarted

    - name: Create terms Solr core
      command: sudo -u solr /opt/solr/bin/solr create -c {{ item }}
      ignore_errors: yes
      tags: terms
      with_items:
        - artist
        - location
        - technique

    - name: Pausing for Solr to finish creating cores..
      pause: seconds=60

    - name: Creating Artist fields in Solr
      uri:
        url: http://localhost:8983/solr/artist/schema
        method: POST
        body:
          add-field:
            name: "{{ item }}"
            type: string
            stored: true
        status_code: 200
        body_format: json
      with_items:
        - label
        - name
        - hint

    - name: Creating Location fields in Solr
      uri:
        url: http://localhost:8983/solr/location/schema
        method: POST
        body:
          add-field:
            name: "{{item}}"
            type: string
            stored: true
        status_code: 200
        body_format: json
      with_items:
        - label
        - name
        - hint

    - name: Creating Technique fields in Solr
      uri:
        url: http://localhost:8983/solr/technique/schema
        method: POST
        body:
          add-field:
            name: "{{item}}"
            type: string
            stored: true
        status_code: 200
        body_format: json
      with_items:
        - label
        - name
        - hint

    - name: Add text_lower field type
      uri:
        url: http://localhost:8983/solr/{{ item }}/schema
        method: POST
        body:
          add-field-type:
            name: text_lower
            class: solr.TextField
            positionIncrementGap: 100
            indexAnalyzer:
              tokenizer:
                class: solr.NGramTokenizerFactory
                minGramSize: 2
                maxGramSize: 10
              filters:
                - class: solr.LowerCaseFilterFactory
            queryAnalyzer:
              tokenizer:
                class: solr.EdgeNGramTokenizerFactory
                minGramSize: 2
                maxGramSize: 10
              filters:
                - class: solr.LowerCaseFilterFactory
        status_code: 200
        body_format: json
      with_items:
        - artist
        - location
        - technique

    - name: Add Ngram-text field type
      uri:
        url: http://localhost:8983/solr/{{ item }}/schema
        method: POST
        body:
          add-field-type:
            name: text_ngram
            class: solr.TextField
            positionIncrementGap: 100
            indexAnalyzer:
              tokenizer:
                class: solr.NGramTokenizerFactory
                minGramSize: 2
                maxGramSize: 10
              filters:
                - class: solr.LowerCaseFilterFactory
            queryAnalyzer:
              tokenizer:
                class: solr.EdgeNGramTokenizerFactory
                minGramSize: 2
                maxGramSize: 10
              filters:
                - class: solr.LowerCaseFilterFactory
        status_code: 200
        body_format: json
      with_items:
        - artist
        - location
        - technique

    - name: Creating Label NGram field in Solr
      uri:
        url: http://localhost:8983/solr/{{ item }}/schema
        method: POST
        body:
          add-field:
            name: label_ngram
            type: text_ngram
            stored: true
        status_code: 200
        body_format: json
      with_items:
        - artist
        - location
        - technique

    - name: Pausing for Solr to catch up..
      pause: seconds=10

    - name: Add Copy Field for label NGram index
      uri:
        url: http://localhost:8983/solr/{{ item }}/schema
        method: POST
        body:
          add-copy-field:
            source: label
            dest:
              - label_ngram
        status_code: 200
        body_format: json
      with_items:
        - artist
        - location
        - technique

    - name: Unpacking terminology archives on server
      unarchive: src={{ item }}.csv.tar.gz dest=/opt/solr/server owner=solr group=solr
      with_items:
        - artist
        - location
        - technique

    - name: Loading terminologies into the Solr indices
      uri:
        url: "http://localhost:8983/solr/{{ item }}/update/csv?stream.file={{ item }}.csv&charset=utf-8&commit=true&fieldnames=label,name,hint,uri"
        method: GET
        timeout: 1000
        status_code: 200
      with_items:
        - artist
        - location
        - technique
